config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'


  get 'welcome/about'

 resources :jobs

 root to: 'jobs#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :find_job, only: [:show, :edit, :update, :destroy]
  
  def index
    if params[:category].blank?
      @jobs = Job.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @jobs = Job.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def show
  end
  
  def edit
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to @job
    else
      render "New"
    end
  end

  def update
    if @job.update(job_params)
      redirect_to @job
    else
      render "Edit"
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to root_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :category_id)
  end

  def find_job
    @job = Job.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, size: '60x6' %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/_form.html.haml
= simple_form_for(@job, html: { class: 'form-hortizontal'}) do |f|
  = f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a job category"}, input_html: { class: "dropdown-toggle" }
  = f.input :title, label: "Job Titie", input_html: { class: "form-controller" }
  = f.input :description, label: "Job Description", input_html: { class: "form-controller" }
  %br/
  = f.button :submit

app/views/jobs/edit.html.erb
<h1>Edit Posting</h1>

<%= render "form" %>

app/views/jobs/edit.html.haml
%h1 Edit job

= render 'form'

= link_to 'Back', root_path

app/views/jobs/index.html.erb
<h1>Available Jobs</h1>
<br>

<% @jobs.each do |job| %>
  <h3><%= link_to job.title, job%></h3>
  <p><%= job.description %></p>
<% end %>

app/views/jobs/index.html.haml
#jobs
  - @jobs.each do |job|
    .job
      %h2= link_to job.title, job

app/views/jobs/new.html.erb
<h1>Add a job</h1>

<%= render "form" %>

app/views/jobs/new.html.haml
%h1 Add a job

= render 'form'

= link_to 'Back', root_path

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>
<h5><%= link_to "Edit Posting", edit_job_path(job)%></h5>
<h5><%= link_to 'Delete Posting', job, method: :delete %></h5>

app/views/jobs/show.html.haml
#jobs
  .job
    %h2= @job.title
    %p= @job.description
    %button.btn.btn-info= link_to "Apply", @job

#links
  = link_to "Back", root_path, class: "btn btn-sm btn-default"
  = link_to "Edit", edit_job_path(@job), class: "btn btn-sm btn-default"
  = link_to "Delete", job_path(@job), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-default"

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Job Board
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags 

%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand Jobs
      %ul.nav.navbar-nav
        %li= link_to "Home ", root_path 
        - Category.all.each do |category|
          %li= link_to category.name, jobs_path(category: category.name)
      = link_to "New Job", new_job_path, class: "navbar-text navbar-right navbar-link"
  .container
    .col-md-6.col-md-offset-3
      = yield



          

app/views/welcome/about.html.erb
<h1>About Job Board</h1>

<p>List jobs for developers</p>

app/views/welcome/index.html.erb
<h1>>Welcome to Job Board</h1>

<p>List jobs</p>